### ISSUE TITLE
THIS CODE SCUKS

### ISSUE THREAD

**Issue by Perthys** [samuelhook/SHSource#1]
THIS CODE SCUKSTHIS CODE SCUKSTHIS CODE SCUKSTHIS CODE SCUKS

**Comment by cerealwithmilk** [comment]
vouch

**Comment by mrbirdz** [comment]
> THIS CODE SCUKSTHIS CODE SCUKSTHIS CODE SCUKSTHIS CODE SCUKS

FUCK YOU PERTH

**Comment by cerealwithmilk** [comment]
> > THIS CODE SCUKSTHIS CODE SCUKSTHIS CODE SCUKSTHIS CODE SCUKS
> 
> FUCK YOU PERTH

aren't you the guy that called an old project of mine skidded and leaked it open sourced code in github lol?

**Comment by mrbirdz** [comment]
> > > THIS CODE SCUKSTHIS CODE SCUKSTHIS CODE SCUKSTHIS CODE SCUKS
> 
> > 
> 
> > FUCK YOU PERTH
> 
> 
> 
> aren't you the guy that called an old project of mine skidded and leaked it open sourced code in github lol?
> 
> edit: yeah you are, fuck you skid :3 

who are u nigga , unknown mf identify yourself
